### ISSUE TITLE
consistency of @prefix for types ==> use mrt + remove underscore ?

### ISSUE THREAD

**Issue by marc-portier** [lifewatch/marineregions-ontology#1]
https://github.com/lifewatch/marineregions-ontology/blob/9c92c643356e6fcbaa148aa32e4e24c78f664850/ontology.ttl#L2

should we not change this to be conform /ns/placetypes.ttl
```@prefix mrt: <http://marineregions.org/ns/placetypes#> .```

**Comment by hdelva** [comment]
Done!
